### ISSUE TITLE
Non Riru/Zygisk version

### ISSUE THREAD

**Issue by bipindr123** [HuskyDG/riru-integrityfix#6]
Since riru is deprecated, I believe a version with Zygisk would be better. There exists a version of play integrity fix by Displax which doesn't use riru, which could be used as reference.

**Comment by HuskyDG** [comment]
Firstly, Zygisk leaves some traces that unable to hide, and there are no modules that can hide Zygisk. Not every app detects for this at the moment. https://t.me/magiskalpha/529
Secondly, the implementation of Zygisk is less effective than Riru's one, even Riru is deprecated but still working on Android 13. And Riru is hard to be found out.
Thirdly, I fork USNF because the original one has deprecated Riru. I will not make a Zygisk version, just use the mod from @Displax
